### ISSUE TITLE
USER STORY: As a Site User, I can create a new recipe so that I can share it with other users

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/Agile#1]
EPIC: Recipe Creation

As a **Site User**, I can **create a new recipe** so that **I can share it with other users**.

**Acceptance Criteria**

- [ ] Recipe form has title, description, category, image and ingredients
- [ ] The user can add as many ingredients as needed
- [ ] The user can preview the recipe before submitting it
- [ ] After submitting the recipe, the user is redirected to the receipe detail page
- [ ] If the user tries to create a recipe without being logged in, they are redirected to the login page

**Tasks**

- [ ] Task 1: Design and implement new recipe item
- [ ] Task 2: Implement recipe upload funcionality
- [ ] Task 3: Add recipe validation and error handling
- [ ] Task 4: Test recipe creation functionality
